# Generated by Django 3.1.3 on 2022-10-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20221019_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer',
        ),
        migrations.AddField(
            model_name='product',
            name='mainfunc',
            field=models.CharField(default='', max_length=10),
        ),
    ]
