# Generated by Django 3.1.3 on 2022-10-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20221025_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='detail_inst',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sales',
            name='main_inst',
            field=models.CharField(default='', max_length=4),
        ),
    ]
