# Generated by Django 3.1.3 on 2022-10-25 06:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0008_auto_20221025_1443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='SalesInfo',
        ),
    ]
