# Generated by Django 3.1.3 on 2022-10-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20221025_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinfo',
            name='amt',
            field=models.IntegerField(default=0),
        ),
    ]
