# Generated by Django 3.1.3 on 2022-10-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20221025_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udate', models.DateTimeField(blank=True, null=True)),
                ('scode', models.CharField(max_length=10)),
                ('sale_date', models.DateTimeField()),
                ('qty', models.IntegerField(default=1)),
                ('amt', models.IntegerField(default=0)),
                ('main_inst', models.CharField(default='', max_length=4)),
                ('detail_inst', models.TextField(default='')),
                ('uexplain', models.CharField(max_length=20)),
            ],
        ),
    ]
